# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

version = 0.1

[default]

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
image_repositories = []
region = "us-east-1"
resolve_s3 = true
s3_prefix = "sam-app"

[default.global.parameters]
stack_name = "sam-app"

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.validate.parameters]
lint = true
