"""This type stub file was generated by pyright."""

from __future__ import annotations

class ContextAPI:
    DEFAULT_CONTEXT = ...
    @classmethod
    def create_context(
        cls,
        name,
        orchestrator=...,
        host=...,
        tls_cfg=...,
        default_namespace=...,
        skip_tls_verify=...,
    ): ...
    @classmethod
    def get_context(cls, name=...): ...
    @classmethod
    def contexts(cls): ...
    @classmethod
    def get_current_context(cls): ...
    @classmethod
    def set_current_context(cls, name=...): ...
    @classmethod
    def remove_context(cls, name): ...
    @classmethod
    def inspect_context(cls, name=...): ...
