"""This type stub file was generated by pyright."""
# pylint: disable=C,E,W
from __future__ import annotations

from typing import Any, Callable, Dict, Optional

from docker.api.client import APIClient
from docker.models.configs import ConfigCollection
from docker.models.containers import ContainerCollection
from docker.models.images import ImageCollection
from docker.models.networks import NetworkCollection
from docker.models.nodes import NodeCollection
from docker.models.plugins import PluginCollection
from docker.models.secrets import SecretCollection
from docker.models.services import ServiceCollection
from docker.models.swarm import Swarm
from docker.models.volumes import VolumeCollection
from typing_extensions import TypedDict

class _DockerClientFromEnvKwargs(TypedDict, total=False):
    assert_hostname: int
    credstore_env: Dict[Any, Any]
    environment: Dict[Any, Any]
    max_pool_size: int
    ssl_version: int
    timeout: int
    use_ssh_client: bool
    version: str

class DockerClient:
    api: APIClient
    def __init__(
        self,
        *args: Any,
        assert_hostname: bool = ...,
        credstore_env: Dict[Any, Any] = ...,
        environment: Dict[str, str] = ...,
        max_pool_size: int = ...,
        ssl_version: int = ...,
        timeout: int = ...,
        use_ssh_client: bool = ...,
        version: str = ...,
    ) -> None: ...
    @classmethod
    def from_env(
        cls,
        *,
        assert_hostname: bool = ...,
        credstore_env: Optional[Dict[Any, Any]] = ...,
        environment: Optional[Dict[str, str]] = ...,
        max_pool_size: int = ...,
        ssl_version: Optional[int] = ...,
        timeout: int = ...,
        use_ssh_client: bool = ...,
        version: str = ...,
    ) -> DockerClient: ...
    @property
    def configs(self) -> ConfigCollection: ...
    @property
    def containers(self) -> ContainerCollection: ...
    @property
    def images(self) -> ImageCollection: ...
    @property
    def networks(self) -> NetworkCollection: ...
    @property
    def nodes(self) -> NodeCollection: ...
    @property
    def plugins(self) -> PluginCollection: ...
    @property
    def secrets(self) -> SecretCollection: ...
    @property
    def services(self) -> ServiceCollection: ...
    @property
    def swarm(self) -> Swarm: ...
    @property
    def volumes(self) -> VolumeCollection: ...
    def events(self, *args: Any, **kwargs: Any) -> Any: ...
    def df(self) -> Any: ...
    def info(self, *args: Any, **kwargs: Any) -> Any: ...
    def login(self, *args: Any, **kwargs: Any) -> Any: ...
    def ping(self, *args: Any, **kwargs: Any) -> Any: ...
    def version(self, *args: Any, **kwargs: Any) -> Any: ...
    def close(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

from_env: Callable[..., DockerClient] = ...
