"""This type stub file was generated by pyright."""

# pylint: disable=C,E,W,R
from __future__ import annotations

class TLSConfig:
    cert = ...
    ca_cert = ...
    verify = ...
    ssl_version = ...
    def __init__(
        self,
        client_cert=...,
        ca_cert=...,
        verify=...,
        ssl_version=...,
        assert_hostname=...,
        assert_fingerprint=...,
    ) -> None: ...
    def configure_client(self, client): ...
