# https://github.com/release-drafter/release-drafter
autolabeler:  # cspell:ignore autolabeler
  - label: bug
    branch: [/^(bug|bugfix|fix|hotfix)\/.*/]
  - label: cloudformation
    files:
      - '**/templates/*.json'
      - '**/templates/*.template'
      - '**/templates/*.yaml'
      - '**/templates/*.yml'
  - label: dependencies
    branch: [/^(depend|dependabot)\/.*/]
  - label: documentation
    branch: [/^(docs)\/.*/]
  - label: feature
    branch: [/^(enhancement|feat|feature)\/.*/]
  - label: github_actions
    files:
      - .github/workflows/*.yml
  - label: javascript
    files:
      - '**/*.js'
      - '**/package-lock.json'
      - '**/package.json'
  - label: maintenance
    branch: [/^(chore|maint|maintain|maintenance)\/.*/]
  - label: npm
    files:
      - npm/.npmignore
      - npm/postinstall.js
      - npm/preuninstall.js
  - label: changelog:patch
    branch: [/^(bug|bugfix|fix|hotfix)\/.*/]
  - label: poetry
    files:
      - poetry.lock
      - poetry.toml
      - pyproject.toml
  - label: pyinstaller
    files:
      - runway.file.spec
      - runway.folder.spec
  - label: python
    files:
      - '**/*.py'
      - poetry.lock
      - pyproject.toml
      - setup.cfg
  - label: release
    branch: [/^(release)\/.*/]
categories:
  - title: ðŸš€ Features
    labels:
      - feature
      - enhancement
  - title: ðŸ› Bug Fixes
    labels:
      - bug
  - title: ðŸ§¶ Dependencies
    labels:
      - dependencies
  - title: ðŸ“– Doc Updates
    labels:
      - documentation
  - title: ðŸ§° Maintenance
    label: maintenance
category-template: >-
  ### $TITLE
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
commitish: master  # cspell:ignore commitish
exclude-labels:
  - changelog:skip
  - release
name-template: v$RESOLVED_VERSION
sort-direction: ascending
tag-template: v$RESOLVED_VERSION
template: |
  ## What Changed

  $CHANGES
version-resolver:
  major:
    labels:
      - changelog:major
  minor:
    labels:
      - changelog:minor
  patch:
    labels:
      - changelog:patch
  default: patch
