# https://github.com/release-drafter/release-drafter
autolabeler:  # cspell:ignore autolabeler
  - label: bug
    branch: [/^(bug|bugfix|fix|hotfix)\/.*/]
  - label: changelog:skip
    branch: [/^(dependabot)\/.*/, /^pre-commit-ci-update-config/, /^renovate\/.*lockfile/]
  - label: dependencies
    branch: [/^(dep|depend|dependabot|deps|renovate)\/.*/]
  - label: documentation
    branch: [/^(docs)\/.*/]
  - label: feature
    branch: [/^(enhancement|feat|feature)\/.*/]
  - label: maintenance
    branch: [/^(chore|maint|maintain|maintenance)\/.*/]
  - label: changelog:patch
    branch: [/^(bug|bugfix|fix|hotfix)\/.*/]
  - label: release
    branch: [/^(release)\/.*/]
categories:
  - title: ðŸš€ Features
    labels:
      - feature
      - enhancement
  - title: ðŸ› Bug Fixes
    labels:
      - bug
  - title: ðŸ§¶ Dependencies
    labels:
      - dependencies
  - title: ðŸ“– Doc Updates
    labels:
      - documentation
  - title: ðŸ§° Maintenance
    label: maintenance
category-template: >-
  ### $TITLE
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
exclude-contributors:
  - dependabot
exclude-labels:
  - changelog:skip
  - release
filter-by-commitish: true  # cspell:ignore commitish
name-template: v$RESOLVED_VERSION
sort-direction: ascending
tag-template: v$RESOLVED_VERSION
template: |
  ## What Changed

  $CHANGES
version-resolver:
  major:
    labels:
      - changelog:major
  minor:
    labels:
      - changelog:minor
  patch:
    labels:
      - changelog:patch
  default: patch
