"""This type stub file was generated by pyright."""

from __future__ import annotations

from awacs.aws import Policy, Statement

def make_simple_assume_statement(*principals: str) -> Statement: ...
def make_simple_assume_policy(*principals: str) -> Policy: ...
def make_service_domain_name(service: str, region: str = ...) -> str:
    """Helper function for creating proper service domain names."""
    ...

def get_codedeploy_assumerole_policy(region: str = ...) -> Policy:
    """Helper function for building the AWS CodeDeploy AssumeRole Policy."""
    ...

def get_default_assumerole_policy(region: str = ...) -> Policy:
    """Helper function for building the Default AssumeRole Policy.

    Taken from here:
        https://github.com/boto/boto/blob/develop/boto/iam/connection.py#L29
    Used to allow ec2 instances to assume the roles in their InstanceProfile.
    """
    ...

def get_ecs_assumerole_policy(region: str = ...) -> Policy:
    """Helper function for building the ECS AssumeRole Policy."""
    ...

def get_ecs_task_assumerole_policy(region: str = ...) -> Policy:
    """Helper function for building the AssumeRole Policy for ECS Tasks."""
    ...

def get_lambda_assumerole_policy(region: str = ...) -> Policy:
    """Helper function for building the AWS Lambda AssumeRole Policy."""
    ...

def get_lambda_edge_assumerole_policy(region: str = ...) -> Policy:
    """Helper function for building the AWS Lambda@Edge AssumeRole Policy."""
    ...

def get_application_autoscaling_assumerole_policy(region: str = ...) -> Policy:
    """Helper function for building the AWS Lambda AssumeRole Policy."""
    ...
