"""
This type stub file was generated by pyright.
"""

"""Retry quota implementation.


"""

class RetryQuota(object):
    INITIAL_CAPACITY = ...
    def __init__(self, initial_capacity=..., lock=...) -> None: ...
    def acquire(self, capacity_amount):
        """Attempt to aquire a certain amount of capacity.

        If there's not sufficient amount of capacity available, ``False``
        is returned.  Otherwise, ``True`` is returned, which indicates that
        capacity was successfully allocated.

        """
        ...

    def release(self, capacity_amount):
        """Release capacity back to the retry quota.

        The capacity being released will be truncated if necessary
        to ensure the max capacity is never exceeded.

        """
        ...

    @property
    def available_capacity(self): ...
