"""
This type stub file was generated by pyright.
"""

from collections import namedtuple

CubicParams = namedtuple("CubicParams", ["w_max", "k", "last_fail"])

class CubicCalculator(object):
    _SCALE_CONSTANT = ...
    _BETA = ...
    def __init__(self, starting_max_rate, start_time, scale_constant=..., beta=...) -> None: ...
    def success_received(self, timestamp): ...
    def error_received(self, current_rate, timestamp): ...
    def get_params_snapshot(self):
        """Return a read-only object of the current cubic parameters.

        These parameters are intended to be used for debug/troubleshooting
        purposes.  These object is a read-only snapshot and cannot be used
        to modify the behavior of the CUBIC calculations.

        New parameters may be added to this object in the future.

        """
        ...
