name: Bug Report
description: File a bug report
title: '[BUG] <title>'
labels:
  - bug
  - priority:low
  - status:review_needed
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for wanting to report a bug in Runway!**

        ⚠ Please make sure that this [issue wasn't already requested][issue search], or already implemented in the master branch.

        [issue search]: https://github.com/rackspace/runway/issues?q=is%3Aissue+is%3Aopen+
  - type: textarea
    attributes:
      label: Bug Description
      description: >-
        What is the bug? Please provide a snippet of Runway's output including
        any errors and the messages logged before the error.
        Verbose or debug logs are preferred but please ensure all secrets and
        other sensitive information has been removed.
      placeholder: I did ... and ... happened.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        What did you expect to happen? For example, expected output or behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: >-
        Please provide the steps that can be used to reproduce this behavior.

        If possible, please include an example project (GitHub repository) that
        is capable of reproducing this behavior.
        The example project should only include the minimum required code
        to reproduce the issue.
        It should not depend on any external resource.
      value: |
        Example project: ...

        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: input
    attributes:
      label: Runway version
      description: This can be found by running `runway --version`.
      placeholder: 0.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: OS / Environment
      description: |
        Provide all relevant information below, e.g. OS version, language versions.

        examples:
          - **OS:** macOS 11
          - **python version:** 3.10.0
          - **npm version:** 7.20.0
          - **terraform version:** 1.0.0
          - **serverless version:** 2.0.0

      placeholder: |
        - OS: macOS 11
        - python version: 3.10.0
        - npm version: 7.20.0
        - terraform version: 1.0.0
        - serverless version: 2.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
