"""This type stub file was generated by pyright."""

from __future__ import annotations

from typing import Callable, TypeVar

from typing_extensions import ParamSpec

_P = ParamSpec("_P")
_RT = TypeVar("_RT")

def check_resource(resource_name: str) -> Callable[[Callable[_P, _RT]], _RT]: ...
def minimum_version(version: str) -> Callable[[Callable[_P, _RT]], _RT]: ...
def update_headers(f: Callable[_P, _RT]) -> Callable[_P, _RT]: ...
