"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Certificate Manager"
prefix = "acm"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

AddTagsToCertificate = Action("AddTagsToCertificate")
DeleteCertificate = Action("DeleteCertificate")
DescribeCertificate = Action("DescribeCertificate")
ExportCertificate = Action("ExportCertificate")
GetCertificate = Action("GetCertificate")
ImportCertificate = Action("ImportCertificate")
ListCertificates = Action("ListCertificates")
ListTagsForCertificate = Action("ListTagsForCertificate")
RemoveTagsFromCertificate = Action("RemoveTagsFromCertificate")
RenewCertificate = Action("RenewCertificate")
RequestCertificate = Action("RequestCertificate")
ResendValidationEmail = Action("ResendValidationEmail")
UpdateCertificateOptions = Action("UpdateCertificateOptions")
