"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Marketplace Management Portal"
prefix = "aws-marketplace-management"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

uploadFiles = Action("uploadFiles")
viewMarketing = Action("viewMarketing")
viewReports = Action("viewReports")
viewSettings = Action("viewSettings")
viewSupport = Action("viewSupport")
