"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Billing"
prefix = "aws-portal"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

ModifyAccount = Action("ModifyAccount")
ModifyBilling = Action("ModifyBilling")
ModifyPaymentMethods = Action("ModifyPaymentMethods")
ViewAccount = Action("ViewAccount")
ViewBilling = Action("ViewBilling")
ViewPaymentMethods = Action("ViewPaymentMethods")
ViewUsage = Action("ViewUsage")
