"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Braket"
prefix = "braket"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CancelQuantumTask = Action("CancelQuantumTask")
CreateQuantumTask = Action("CreateQuantumTask")
GetDevice = Action("GetDevice")
GetQuantumTask = Action("GetQuantumTask")
SearchDevices = Action("SearchDevices")
SearchQuantumTasks = Action("SearchQuantumTasks")
