"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Budget Service"
prefix = "budgets"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CreateBudgetAction = Action("CreateBudgetAction")
DeleteBudgetAction = Action("DeleteBudgetAction")
DescribeBudgetAction = Action("DescribeBudgetAction")
DescribeBudgetActionHistories = Action("DescribeBudgetActionHistories")
DescribeBudgetActionsForAccount = Action("DescribeBudgetActionsForAccount")
DescribeBudgetActionsForBudget = Action("DescribeBudgetActionsForBudget")
ExecuteBudgetAction = Action("ExecuteBudgetAction")
ModifyBudget = Action("ModifyBudget")
UpdateBudgetAction = Action("UpdateBudgetAction")
ViewBudget = Action("ViewBudget")
