"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Keyspaces (for Apache Cassandra)"
prefix = "cassandra"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

Alter = Action("Alter")
Create = Action("Create")
Drop = Action("Drop")
Modify = Action("Modify")
Restore = Action("Restore")
Select = Action("Select")
TagResource = Action("TagResource")
UntagResource = Action("UntagResource")
