"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS CloudTrail"
prefix = "cloudtrail"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

AddTags = Action("AddTags")
CreateTrail = Action("CreateTrail")
DeleteTrail = Action("DeleteTrail")
DescribeTrails = Action("DescribeTrails")
GetEventSelectors = Action("GetEventSelectors")
GetInsightSelectors = Action("GetInsightSelectors")
GetTrail = Action("GetTrail")
GetTrailStatus = Action("GetTrailStatus")
ListPublicKeys = Action("ListPublicKeys")
ListTags = Action("ListTags")
ListTrails = Action("ListTrails")
LookupEvents = Action("LookupEvents")
PutEventSelectors = Action("PutEventSelectors")
PutInsightSelectors = Action("PutInsightSelectors")
RemoveTags = Action("RemoveTags")
StartLogging = Action("StartLogging")
StopLogging = Action("StopLogging")
UpdateTrail = Action("UpdateTrail")
