"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Cloud9"
prefix = "cloud9"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CreateEnvironmentEC2 = Action("CreateEnvironmentEC2")
CreateEnvironmentMembership = Action("CreateEnvironmentMembership")
CreateEnvironmentSSH = Action("CreateEnvironmentSSH")
DeleteEnvironment = Action("DeleteEnvironment")
DeleteEnvironmentMembership = Action("DeleteEnvironmentMembership")
DescribeEnvironmentMemberships = Action("DescribeEnvironmentMemberships")
DescribeEnvironmentStatus = Action("DescribeEnvironmentStatus")
DescribeEnvironments = Action("DescribeEnvironments")
GetUserPublicKey = Action("GetUserPublicKey")
GetUserSettings = Action("GetUserSettings")
ListEnvironments = Action("ListEnvironments")
ListTagsForResource = Action("ListTagsForResource")
TagResource = Action("TagResource")
UntagResource = Action("UntagResource")
UpdateEnvironment = Action("UpdateEnvironment")
UpdateEnvironmentMembership = Action("UpdateEnvironmentMembership")
UpdateUserSettings = Action("UpdateUserSettings")
ValidateEnvironmentName = Action("ValidateEnvironmentName")
