"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon CodeGuru Reviewer"
prefix = "codeguru-reviewer"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

AssociateRepository = Action("AssociateRepository")
CreateConnectionToken = Action("CreateConnectionToken")
DescribeCodeReview = Action("DescribeCodeReview")
DescribeRecommendationFeedback = Action("DescribeRecommendationFeedback")
DescribeRepositoryAssociation = Action("DescribeRepositoryAssociation")
DisassociateRepository = Action("DisassociateRepository")
GetMetricsData = Action("GetMetricsData")
ListCodeReviews = Action("ListCodeReviews")
ListRecommendationFeedback = Action("ListRecommendationFeedback")
ListRecommendations = Action("ListRecommendations")
ListRepositoryAssociations = Action("ListRepositoryAssociations")
ListThirdPartyRepositories = Action("ListThirdPartyRepositories")
PutRecommendationFeedback = Action("PutRecommendationFeedback")
