"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon CodeGuru"
prefix = "codeguru"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

GetCodeGuruFreeTrialSummary = Action("GetCodeGuruFreeTrialSummary")
