"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS CodeStar Notifications"
prefix = "codestar-notifications"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CreateNotificationRule = Action("CreateNotificationRule")
DeleteNotificationRule = Action("DeleteNotificationRule")
DeleteTarget = Action("DeleteTarget")
DescribeNotificationRule = Action("DescribeNotificationRule")
ListEventTypes = Action("ListEventTypes")
ListNotificationRules = Action("ListNotificationRules")
ListTagsForResource = Action("ListTagsForResource")
ListTargets = Action("ListTargets")
Subscribe = Action("Subscribe")
TagResource = Action("TagResource")
Unsubscribe = Action("Unsubscribe")
UntagResource = Action("UntagResource")
UpdateNotificationRule = Action("UpdateNotificationRule")
