"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS CodeStar"
prefix = "codestar"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

AssociateTeamMember = Action("AssociateTeamMember")
CreateProject = Action("CreateProject")
CreateUserProfile = Action("CreateUserProfile")
DeleteExtendedAccess = Action("DeleteExtendedAccess")
DeleteProject = Action("DeleteProject")
DeleteUserProfile = Action("DeleteUserProfile")
DescribeProject = Action("DescribeProject")
DescribeUserProfile = Action("DescribeUserProfile")
DisassociateTeamMember = Action("DisassociateTeamMember")
GetExtendedAccess = Action("GetExtendedAccess")
ListProjects = Action("ListProjects")
ListResources = Action("ListResources")
ListTagsForProject = Action("ListTagsForProject")
ListTeamMembers = Action("ListTeamMembers")
ListUserProfiles = Action("ListUserProfiles")
PutExtendedAccess = Action("PutExtendedAccess")
TagProject = Action("TagProject")
UntagProject = Action("UntagProject")
UpdateProject = Action("UpdateProject")
UpdateTeamMember = Action("UpdateTeamMember")
UpdateUserProfile = Action("UpdateUserProfile")
VerifyServiceRole = Action("VerifyServiceRole")
