"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Cognito Identity"
prefix = "cognito-identity"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CreateIdentityPool = Action("CreateIdentityPool")
DeleteIdentities = Action("DeleteIdentities")
DeleteIdentityPool = Action("DeleteIdentityPool")
DescribeIdentity = Action("DescribeIdentity")
DescribeIdentityPool = Action("DescribeIdentityPool")
GetCredentialsForIdentity = Action("GetCredentialsForIdentity")
GetId = Action("GetId")
GetIdentityPoolRoles = Action("GetIdentityPoolRoles")
GetOpenIdToken = Action("GetOpenIdToken")
GetOpenIdTokenForDeveloperIdentity = Action("GetOpenIdTokenForDeveloperIdentity")
ListIdentities = Action("ListIdentities")
ListIdentityPools = Action("ListIdentityPools")
ListTagsForResource = Action("ListTagsForResource")
LookupDeveloperIdentity = Action("LookupDeveloperIdentity")
MergeDeveloperIdentities = Action("MergeDeveloperIdentities")
SetIdentityPoolRoles = Action("SetIdentityPoolRoles")
TagResource = Action("TagResource")
UnlinkDeveloperIdentity = Action("UnlinkDeveloperIdentity")
UnlinkIdentity = Action("UnlinkIdentity")
UntagResource = Action("UntagResource")
UpdateIdentityPool = Action("UpdateIdentityPool")
