"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Cognito Sync"
prefix = "cognito-sync"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

BulkPublish = Action("BulkPublish")
DeleteDataset = Action("DeleteDataset")
DescribeDataset = Action("DescribeDataset")
DescribeIdentityPoolUsage = Action("DescribeIdentityPoolUsage")
DescribeIdentityUsage = Action("DescribeIdentityUsage")
GetBulkPublishDetails = Action("GetBulkPublishDetails")
GetCognitoEvents = Action("GetCognitoEvents")
GetIdentityPoolConfiguration = Action("GetIdentityPoolConfiguration")
ListDatasets = Action("ListDatasets")
ListIdentityPoolUsage = Action("ListIdentityPoolUsage")
ListRecords = Action("ListRecords")
QueryRecords = Action("QueryRecords")
RegisterDevice = Action("RegisterDevice")
SetCognitoEvents = Action("SetCognitoEvents")
SetDatasetConfiguration = Action("SetDatasetConfiguration")
SetIdentityPoolConfiguration = Action("SetIdentityPoolConfiguration")
SubscribeToDataset = Action("SubscribeToDataset")
UnsubscribeFromDataset = Action("UnsubscribeFromDataset")
UpdateRecords = Action("UpdateRecords")
