"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Kinesis Firehose"
prefix = "firehose"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CreateDeliveryStream = Action("CreateDeliveryStream")
DeleteDeliveryStream = Action("DeleteDeliveryStream")
DescribeDeliveryStream = Action("DescribeDeliveryStream")
ListDeliveryStreams = Action("ListDeliveryStreams")
ListTagsForDeliveryStream = Action("ListTagsForDeliveryStream")
PutRecord = Action("PutRecord")
PutRecordBatch = Action("PutRecordBatch")
StartDeliveryStreamEncryption = Action("StartDeliveryStreamEncryption")
StopDeliveryStreamEncryption = Action("StopDeliveryStreamEncryption")
TagDeliveryStream = Action("TagDeliveryStream")
UntagDeliveryStream = Action("UntagDeliveryStream")
UpdateDestination = Action("UpdateDestination")
