"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon GroundTruth Labeling"
prefix = "groundtruthlabeling"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

DescribeConsoleJob = Action("DescribeConsoleJob")
ListDatasetObjects = Action("ListDatasetObjects")
RunFilterOrSampleDatasetJob = Action("RunFilterOrSampleDatasetJob")
RunGenerateManifestByCrawlingJob = Action("RunGenerateManifestByCrawlingJob")
