"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Honeycode"
prefix = "honeycode"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

ApproveTeamAssociation = Action("ApproveTeamAssociation")
GetScreenData = Action("GetScreenData")
InvokeScreenAutomation = Action("InvokeScreenAutomation")
ListTeamAssociations = Action("ListTeamAssociations")
RejectTeamAssociation = Action("RejectTeamAssociation")
