"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Import Export Disk Service"
prefix = "importexport"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CancelJob = Action("CancelJob")
CreateJob = Action("CreateJob")
GetShippingLabel = Action("GetShippingLabel")
GetStatus = Action("GetStatus")
ListJobs = Action("ListJobs")
UpdateJob = Action("UpdateJob")
