"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS IoT Device Tester"
prefix = "iot-device-tester"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CheckVersion = Action("CheckVersion")
DownloadTestSuite = Action("DownloadTestSuite")
LatestIdt = Action("LatestIdt")
SendMetrics = Action("SendMetrics")
SupportedVersion = Action("SupportedVersion")
