"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Launch Wizard"
prefix = "launchwizard"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

DeleteApp = Action("DeleteApp")
DescribeProvisionedApp = Action("DescribeProvisionedApp")
DescribeProvisioningEvents = Action("DescribeProvisioningEvents")
GetInfrastructureSuggestion = Action("GetInfrastructureSuggestion")
GetIpAddress = Action("GetIpAddress")
GetResourceCostEstimate = Action("GetResourceCostEstimate")
ListProvisionedApps = Action("ListProvisionedApps")
StartProvisioning = Action("StartProvisioning")
