"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Managed Blockchain"
prefix = "managedblockchain"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CreateMember = Action("CreateMember")
CreateNetwork = Action("CreateNetwork")
CreateNode = Action("CreateNode")
CreateProposal = Action("CreateProposal")
DeleteMember = Action("DeleteMember")
DeleteNode = Action("DeleteNode")
GetMember = Action("GetMember")
GetNetwork = Action("GetNetwork")
GetNode = Action("GetNode")
GetProposal = Action("GetProposal")
ListInvitations = Action("ListInvitations")
ListMembers = Action("ListMembers")
ListNetworks = Action("ListNetworks")
ListNodes = Action("ListNodes")
ListProposalVotes = Action("ListProposalVotes")
ListProposals = Action("ListProposals")
RejectInvitation = Action("RejectInvitation")
UpdateMember = Action("UpdateMember")
UpdateNode = Action("UpdateNode")
VoteOnProposal = Action("VoteOnProposal")
