"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Elemental MediaPackage VOD"
prefix = "mediapackage-vod"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CreateAsset = Action("CreateAsset")
CreatePackagingConfiguration = Action("CreatePackagingConfiguration")
CreatePackagingGroup = Action("CreatePackagingGroup")
DeleteAsset = Action("DeleteAsset")
DeletePackagingConfiguration = Action("DeletePackagingConfiguration")
DeletePackagingGroup = Action("DeletePackagingGroup")
DescribeAsset = Action("DescribeAsset")
DescribePackagingConfiguration = Action("DescribePackagingConfiguration")
DescribePackagingGroup = Action("DescribePackagingGroup")
ListAssets = Action("ListAssets")
ListPackagingConfigurations = Action("ListPackagingConfigurations")
ListPackagingGroups = Action("ListPackagingGroups")
ListTagsForResource = Action("ListTagsForResource")
TagResource = Action("TagResource")
UntagResource = Action("UntagResource")
