"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Migration Hub"
prefix = "mgh"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

AssociateCreatedArtifact = Action("AssociateCreatedArtifact")
AssociateDiscoveredResource = Action("AssociateDiscoveredResource")
CreateHomeRegionControl = Action("CreateHomeRegionControl")
CreateProgressUpdateStream = Action("CreateProgressUpdateStream")
DeleteProgressUpdateStream = Action("DeleteProgressUpdateStream")
DescribeApplicationState = Action("DescribeApplicationState")
DescribeHomeRegionControls = Action("DescribeHomeRegionControls")
DescribeMigrationTask = Action("DescribeMigrationTask")
DisassociateCreatedArtifact = Action("DisassociateCreatedArtifact")
DisassociateDiscoveredResource = Action("DisassociateDiscoveredResource")
GetHomeRegion = Action("GetHomeRegion")
ImportMigrationTask = Action("ImportMigrationTask")
ListCreatedArtifacts = Action("ListCreatedArtifacts")
ListDiscoveredResources = Action("ListDiscoveredResources")
ListMigrationTasks = Action("ListMigrationTasks")
ListProgressUpdateStreams = Action("ListProgressUpdateStreams")
NotifyApplicationState = Action("NotifyApplicationState")
NotifyMigrationTaskState = Action("NotifyMigrationTaskState")
PutResourceAttributes = Action("PutResourceAttributes")
