"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Mobile Analytics"
prefix = "mobileanalytics"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

GetFinancialReports = Action("GetFinancialReports")
GetReports = Action("GetReports")
PutEvents = Action("PutEvents")
