"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS OpsWorks Configuration Management"
prefix = "opsworks-cm"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

AssociateNode = Action("AssociateNode")
CreateBackup = Action("CreateBackup")
CreateServer = Action("CreateServer")
DeleteBackup = Action("DeleteBackup")
DeleteServer = Action("DeleteServer")
DescribeAccountAttributes = Action("DescribeAccountAttributes")
DescribeBackups = Action("DescribeBackups")
DescribeEvents = Action("DescribeEvents")
DescribeNodeAssociationStatus = Action("DescribeNodeAssociationStatus")
DescribeServers = Action("DescribeServers")
DisassociateNode = Action("DisassociateNode")
RestoreServer = Action("RestoreServer")
StartMaintenance = Action("StartMaintenance")
UpdateServer = Action("UpdateServer")
UpdateServerEngineAttributes = Action("UpdateServerEngineAttributes")
