"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Purchase Orders Console"
prefix = "purchase-orders"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

ModifyPurchaseOrders = Action("ModifyPurchaseOrders")
ViewPurchaseOrders = Action("ViewPurchaseOrders")
