"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Tag Editor"
prefix = "resource-explorer"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

ListResourceTypes = Action("ListResourceTypes")
ListResources = Action("ListResources")
ListTags = Action("ListTags")
