"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Resource Groups"
prefix = "resource-groups"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CreateGroup = Action("CreateGroup")
DeleteGroup = Action("DeleteGroup")
GetGroup = Action("GetGroup")
GetGroupQuery = Action("GetGroupQuery")
GetTags = Action("GetTags")
ListGroupResources = Action("ListGroupResources")
ListGroups = Action("ListGroups")
SearchResources = Action("SearchResources")
Tag = Action("Tag")
Untag = Action("Untag")
UpdateGroup = Action("UpdateGroup")
UpdateGroupQuery = Action("UpdateGroupQuery")
