"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Route 53 Resolver"
prefix = "route53resolver"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

AssociateResolverEndpointIpAddress = Action("AssociateResolverEndpointIpAddress")
AssociateResolverQueryLogConfig = Action("AssociateResolverQueryLogConfig")
AssociateResolverRule = Action("AssociateResolverRule")
CreateResolverEndpoint = Action("CreateResolverEndpoint")
CreateResolverQueryLogConfig = Action("CreateResolverQueryLogConfig")
CreateResolverRule = Action("CreateResolverRule")
DeleteResolverEndpoint = Action("DeleteResolverEndpoint")
DeleteResolverQueryLogConfig = Action("DeleteResolverQueryLogConfig")
DeleteResolverRule = Action("DeleteResolverRule")
DisassociateResolverEndpointIpAddress = Action("DisassociateResolverEndpointIpAddress")
DisassociateResolverQueryLogConfig = Action("DisassociateResolverQueryLogConfig")
DisassociateResolverRule = Action("DisassociateResolverRule")
GetResolverEndpoint = Action("GetResolverEndpoint")
GetResolverQueryLogConfig = Action("GetResolverQueryLogConfig")
GetResolverQueryLogConfigAssociation = Action("GetResolverQueryLogConfigAssociation")
GetResolverQueryLogConfigPolicy = Action("GetResolverQueryLogConfigPolicy")
GetResolverRule = Action("GetResolverRule")
GetResolverRuleAssociation = Action("GetResolverRuleAssociation")
GetResolverRulePolicy = Action("GetResolverRulePolicy")
ListResolverEndpointIpAddresses = Action("ListResolverEndpointIpAddresses")
ListResolverEndpoints = Action("ListResolverEndpoints")
ListResolverQueryLogConfigAssociations = Action("ListResolverQueryLogConfigAssociations")
ListResolverQueryLogConfigs = Action("ListResolverQueryLogConfigs")
ListResolverRuleAssociations = Action("ListResolverRuleAssociations")
ListResolverRules = Action("ListResolverRules")
ListTagsForResource = Action("ListTagsForResource")
PutResolverQueryLogConfigPolicy = Action("PutResolverQueryLogConfigPolicy")
PutResolverRulePolicy = Action("PutResolverRulePolicy")
TagResource = Action("TagResource")
UntagResource = Action("UntagResource")
UpdateResolverEndpoint = Action("UpdateResolverEndpoint")
UpdateResolverRule = Action("UpdateResolverRule")
