"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon SimpleDB"
prefix = "sdb"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

class SDB_ARN(ARN):
    def __init__(self, *args, **kwargs) -> None: ...

BatchDeleteAttributes = Action("BatchDeleteAttributes")
BatchPutAttributes = Action("BatchPutAttributes")
CreateDomain = Action("CreateDomain")
DeleteAttributes = Action("DeleteAttributes")
DeleteDomain = Action("DeleteDomain")
DomainMetadata = Action("DomainMetadata")
GetAttributes = Action("GetAttributes")
ListDomains = Action("ListDomains")
PutAttributes = Action("PutAttributes")
Select = Action("Select")
