"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "AWS Serverless Application Repository"
prefix = "serverlessrepo"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CreateApplication = Action("CreateApplication")
CreateApplicationVersion = Action("CreateApplicationVersion")
CreateCloudFormationChangeSet = Action("CreateCloudFormationChangeSet")
CreateCloudFormationTemplate = Action("CreateCloudFormationTemplate")
DeleteApplication = Action("DeleteApplication")
GetApplication = Action("GetApplication")
GetApplicationPolicy = Action("GetApplicationPolicy")
GetCloudFormationTemplate = Action("GetCloudFormationTemplate")
ListApplicationDependencies = Action("ListApplicationDependencies")
ListApplicationVersions = Action("ListApplicationVersions")
ListApplications = Action("ListApplications")
PutApplicationPolicy = Action("PutApplicationPolicy")
SearchApplications = Action("SearchApplications")
UnshareApplication = Action("UnshareApplication")
UpdateApplication = Action("UpdateApplication")
