"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Pinpoint SMS and Voice Service"
prefix = "sms-voice"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CreateConfigurationSet = Action("CreateConfigurationSet")
CreateConfigurationSetEventDestination = Action("CreateConfigurationSetEventDestination")
DeleteConfigurationSet = Action("DeleteConfigurationSet")
DeleteConfigurationSetEventDestination = Action("DeleteConfigurationSetEventDestination")
GetConfigurationSetEventDestinations = Action("GetConfigurationSetEventDestinations")
ListConfigurationSets = Action("ListConfigurationSets")
SendVoiceMessage = Action("SendVoiceMessage")
UpdateConfigurationSetEventDestination = Action("UpdateConfigurationSetEventDestination")
