"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Session Manager Message Gateway Service"
prefix = "ssmmessages"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

CreateControlChannel = Action("CreateControlChannel")
CreateDataChannel = Action("CreateDataChannel")
OpenControlChannel = Action("OpenControlChannel")
OpenDataChannel = Action("OpenDataChannel")
