"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon Translate"
prefix = "translate"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

DeleteTerminology = Action("DeleteTerminology")
DescribeTextTranslationJob = Action("DescribeTextTranslationJob")
GetTerminology = Action("GetTerminology")
ImportTerminology = Action("ImportTerminology")
ListTerminologies = Action("ListTerminologies")
ListTextTranslationJobs = Action("ListTextTranslationJobs")
StartTextTranslationJob = Action("StartTextTranslationJob")
StopTextTranslationJob = Action("StopTextTranslationJob")
TranslateText = Action("TranslateText")
