"""
This type stub file was generated by pyright.
"""

from .aws import Action as BaseAction
from .aws import BaseARN

service_name = "Amazon WorkLink"
prefix = "worklink"

class Action(BaseAction):
    def __init__(self, action=...) -> None: ...

class ARN(BaseARN):
    def __init__(self, resource=..., region=..., account=...) -> None: ...

AssociateDomain = Action("AssociateDomain")
AssociateWebsiteAuthorizationProvider = Action("AssociateWebsiteAuthorizationProvider")
AssociateWebsiteCertificateAuthority = Action("AssociateWebsiteCertificateAuthority")
CreateFleet = Action("CreateFleet")
DeleteFleet = Action("DeleteFleet")
DescribeAuditStreamConfiguration = Action("DescribeAuditStreamConfiguration")
DescribeCompanyNetworkConfiguration = Action("DescribeCompanyNetworkConfiguration")
DescribeDevice = Action("DescribeDevice")
DescribeDevicePolicyConfiguration = Action("DescribeDevicePolicyConfiguration")
DescribeDomain = Action("DescribeDomain")
DescribeFleetMetadata = Action("DescribeFleetMetadata")
DescribeIdentityProviderConfiguration = Action("DescribeIdentityProviderConfiguration")
DescribeWebsiteCertificateAuthority = Action("DescribeWebsiteCertificateAuthority")
DisassociateDomain = Action("DisassociateDomain")
DisassociateWebsiteAuthorizationProvider = Action("DisassociateWebsiteAuthorizationProvider")
DisassociateWebsiteCertificateAuthority = Action("DisassociateWebsiteCertificateAuthority")
ListDevices = Action("ListDevices")
ListDomains = Action("ListDomains")
ListFleets = Action("ListFleets")
ListTagsForResource = Action("ListTagsForResource")
ListWebsiteAuthorizationProviders = Action("ListWebsiteAuthorizationProviders")
ListWebsiteCertificateAuthorities = Action("ListWebsiteCertificateAuthorities")
RestoreDomainAccess = Action("RestoreDomainAccess")
RevokeDomainAccess = Action("RevokeDomainAccess")
SignOutUser = Action("SignOutUser")
TagResource = Action("TagResource")
UntagResource = Action("UntagResource")
UpdateAuditStreamConfiguration = Action("UpdateAuditStreamConfiguration")
UpdateCompanyNetworkConfiguration = Action("UpdateCompanyNetworkConfiguration")
UpdateDevicePolicyConfiguration = Action("UpdateDevicePolicyConfiguration")
UpdateDomainMetadata = Action("UpdateDomainMetadata")
UpdateFleetMetadata = Action("UpdateFleetMetadata")
UpdateIdentityProviderConfiguration = Action("UpdateIdentityProviderConfiguration")
