"""This type stub file was generated by pyright."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from logging import Logger

logger: Logger = ...

class Task:
    def __init__(
        self,
        transfer_coordinator,
        main_kwargs=...,
        pending_main_kwargs=...,
        done_callbacks=...,
        is_final=...,
    ) -> None: ...
    def __repr__(self): ...
    @property
    def transfer_id(self): ...
    def __call__(self): ...

class SubmissionTask(Task): ...
class CreateMultipartUploadTask(Task): ...
class CompleteMultipartUploadTask(Task): ...
