"""
This type stub file was generated by pyright.
"""

import logging

from botocore import utils

"""This module contains the inteface for controlling how configuration
is loaded.
"""
logger = logging.getLogger(__name__)
BOTOCORE_DEFAUT_SESSION_VARIABLES = {
    "profile": (None, ["AWS_DEFAULT_PROFILE", "AWS_PROFILE"], None, None),
    "region": ("region", "AWS_DEFAULT_REGION", None, None),
    "data_path": ("data_path", "AWS_DATA_PATH", None, None),
    "config_file": (None, "AWS_CONFIG_FILE", "~/.aws/config", None),
    "ca_bundle": ("ca_bundle", "AWS_CA_BUNDLE", None, None),
    "api_versions": ("api_versions", None, {}, None),
    "credentials_file": (
        None,
        "AWS_SHARED_CREDENTIALS_FILE",
        "~/.aws/credentials",
        None,
    ),
    "metadata_service_timeout": (
        "metadata_service_timeout",
        "AWS_METADATA_SERVICE_TIMEOUT",
        1,
        int,
    ),
    "metadata_service_num_attempts": (
        "metadata_service_num_attempts",
        "AWS_METADATA_SERVICE_NUM_ATTEMPTS",
        1,
        int,
    ),
    "ec2_metadata_service_endpoint": (
        "ec2_metadata_service_endpoint",
        "AWS_EC2_METADATA_SERVICE_ENDPOINT",
        None,
        None,
    ),
    "imds_use_ipv6": ("imds_use_ipv6", "AWS_IMDS_USE_IPV6", False, None),
    "parameter_validation": ("parameter_validation", None, True, None),
    "csm_enabled": ("csm_enabled", "AWS_CSM_ENABLED", False, utils.ensure_boolean),
    "csm_host": ("csm_host", "AWS_CSM_HOST", "127.0.0.1", None),
    "csm_port": ("csm_port", "AWS_CSM_PORT", 31000, int),
    "csm_client_id": ("csm_client_id", "AWS_CSM_CLIENT_ID", "", None),
    "endpoint_discovery_enabled": (
        "endpoint_discovery_enabled",
        "AWS_ENDPOINT_DISCOVERY_ENABLED",
        "auto",
        None,
    ),
    "sts_regional_endpoints": (
        "sts_regional_endpoints",
        "AWS_STS_REGIONAL_ENDPOINTS",
        "legacy",
        None,
    ),
    "retry_mode": ("retry_mode", "AWS_RETRY_MODE", "legacy", None),
    "max_attempts": ("max_attempts", "AWS_MAX_ATTEMPTS", None, int),
}
DEFAULT_S3_CONFIG_VARS = {
    "addressing_style": (("s3", "addressing_style"), None, None, None),
    "use_accelerate_endpoint": (
        ("s3", "use_accelerate_endpoint"),
        None,
        None,
        utils.ensure_boolean,
    ),
    "use_dualstack_endpoint": (
        ("s3", "use_dualstack_endpoint"),
        None,
        None,
        utils.ensure_boolean,
    ),
    "payload_signing_enabled": (
        ("s3", "payload_signing_enabled"),
        None,
        None,
        utils.ensure_boolean,
    ),
    "use_arn_region": (
        ["s3_use_arn_region", ("s3", "use_arn_region")],
        "AWS_S3_USE_ARN_REGION",
        None,
        utils.ensure_boolean,
    ),
    "us_east_1_regional_endpoint": (
        ["s3_us_east_1_regional_endpoint", ("s3", "us_east_1_regional_endpoint")],
        "AWS_S3_US_EAST_1_REGIONAL_ENDPOINT",
        None,
        None,
    ),
}
DEFAULT_PROXIES_CONFIG_VARS = {
    "proxy_ca_bundle": ("proxy_ca_bundle", None, None, None),
    "proxy_client_cert": ("proxy_client_cert", None, None, None),
    "proxy_use_forwarding_for_https": (
        "proxy_use_forwarding_for_https",
        None,
        None,
        utils.normalize_boolean,
    ),
}

def create_botocore_default_config_mapping(session): ...

class ConfigChainFactory(object):
    """Factory class to create our most common configuration chain case.

    This is a convenience class to construct configuration chains that follow
    our most common pattern. This is to prevent ordering them incorrectly,
    and to make the config chain construction more readable.
    """

    def __init__(self, session, environ=...) -> None:
        """Initialize a ConfigChainFactory.

        :type session: :class:`botocore.session.Session`
        :param session: This is the session that should be used to look up
            values from the config file.

        :type environ: dict
        :param environ: A mapping to use for environment variables. If this
            is not provided it will default to use os.environ.
        """
        ...

    def create_config_chain(
        self,
        instance_name=...,
        env_var_names=...,
        config_property_names=...,
        default=...,
        conversion_func=...,
    ):
        """Build a config chain following the standard botocore pattern.

        In botocore most of our config chains follow the the precendence:
        session_instance_variables, environment, config_file, default_value.

        This is a convenience function for creating a chain that follow
        that precendence.

        :type instance_name: str
        :param instance_name: This indicates what session instance variable
            corresponds to this config value. If it is None it will not be
            added to the chain.

        :type env_var_names: str or list of str or None
        :param env_var_names: One or more environment variable names to
            search for this value. They are searched in order. If it is None
            it will not be added to the chain.

        :type config_property_names: str/tuple or list of str/tuple or None
        :param config_property_names: One of more strings or tuples
            representing the name of the key in the config file for this
            config option. They are searched in order. If it is None it will
            not be added to the chain.

        :type default: Any
        :param default: Any constant value to be returned.

        :type conversion_func: None or callable
        :param conversion_func: If this value is None then it has no effect on
            the return type. Otherwise, it is treated as a function that will
            conversion_func our provided type.

        :rvalue: ConfigChain
        :returns: A ConfigChain that resolves in the order env_var_names ->
            config_property_name -> default. Any values that were none are
            omitted form the chain.
        """
        ...

class ConfigValueStore(object):
    """The ConfigValueStore object stores configuration values."""

    def __init__(self, mapping=...) -> None:
        """Initialize a ConfigValueStore.

        :type mapping: dict
        :param mapping: The mapping parameter is a map of string to a subclass
            of BaseProvider. When a config variable is asked for via the
            get_config_variable method, the corresponding provider will be
            invoked to load the value.
        """
        ...

    def get_config_variable(self, logical_name):
        """
        Retrieve the value associeated with the specified logical_name
        from the corresponding provider. If no value is found None will
        be returned.

        :type logical_name: str
        :param logical_name: The logical name of the session variable
            you want to retrieve.  This name will be mapped to the
            appropriate environment variable name for this session as
            well as the appropriate config file entry.

        :returns: value of variable or None if not defined.
        """
        ...

    def set_config_variable(self, logical_name, value):
        """Set a configuration variable to a specific value.

        By using this method, you can override the normal lookup
        process used in ``get_config_variable`` by explicitly setting
        a value.  Subsequent calls to ``get_config_variable`` will
        use the ``value``.  This gives you per-session specific
        configuration values.

        ::
            >>> # Assume logical name 'foo' maps to env var 'FOO'
            >>> os.environ['FOO'] = 'myvalue'
            >>> s.get_config_variable('foo')
            'myvalue'
            >>> s.set_config_variable('foo', 'othervalue')
            >>> s.get_config_variable('foo')
            'othervalue'

        :type logical_name: str
        :param logical_name: The logical name of the session variable
            you want to set.  These are the keys in ``SESSION_VARIABLES``.

        :param value: The value to associate with the config variable.
        """
        ...

    def clear_config_variable(self, logical_name):
        """Remove an override config variable from the session.

        :type logical_name: str
        :param logical_name: The name of the parameter to clear the override
            value from.
        """
        ...

    def set_config_provider(self, logical_name, provider):
        """Set the provider for a config value.

        This provides control over how a particular configuration value is
        loaded. This replaces the provider for ``logical_name`` with the new
        ``provider``.

        :type logical_name: str
        :param logical_name: The name of the config value to change the config
            provider for.

        :type provider: :class:`botocore.configprovider.BaseProvider`
        :param provider: The new provider that should be responsible for
            providing a value for the config named ``logical_name``.
        """
        ...

class BaseProvider(object):
    """Base class for configuration value providers.

    A configuration provider has some method of providing a configuration
    value.
    """

    def provide(self):
        """Provide a config value."""
        ...

class ChainProvider(BaseProvider):
    """This provider wraps one or more other providers.

    Each provider in the chain is called, the first one returning a non-None
    value is then returned.
    """

    def __init__(self, providers=..., conversion_func=...) -> None:
        """Initalize a ChainProvider.

        :type providers: list
        :param providers: The initial list of providers to check for values
            when invoked.

        :type conversion_func: None or callable
        :param conversion_func: If this value is None then it has no affect on
            the return type. Otherwise, it is treated as a function that will
            transform provided value.
        """
        ...

    def provide(self):
        """Provide the value from the first provider to return non-None.

        Each provider in the chain has its provide method called. The first
        one in the chain to return a non-None value is the returned from the
        ChainProvider. When no non-None value is found, None is returned.
        """
        ...

    def __repr__(self): ...

class InstanceVarProvider(BaseProvider):
    """This class loads config values from the session instance vars."""

    def __init__(self, instance_var, session) -> None:
        """Initialize InstanceVarProvider.

        :type instance_var: str
        :param instance_var: The instance variable to load from the session.

        :type session: :class:`botocore.session.Session`
        :param session: The botocore session to get the loaded configuration
            file variables from.
        """
        ...

    def provide(self):
        """Provide a config value from the session instance vars."""
        ...

    def __repr__(self): ...

class ScopedConfigProvider(BaseProvider):
    def __init__(self, config_var_name, session) -> None:
        """Initialize ScopedConfigProvider.

        :type config_var_name: str or tuple
        :param config_var_name: The name of the config variable to load from
            the configuration file. If the value is a tuple, it must only
            consist of two items, where the first item represents the section
            and the second item represents the config var name in the section.

        :type session: :class:`botocore.session.Session`
        :param session: The botocore session to get the loaded configuration
            file variables from.
        """
        ...

    def provide(self):
        """Provide a value from a config file property."""
        ...

    def __repr__(self): ...

class EnvironmentProvider(BaseProvider):
    """This class loads config values from environment variables."""

    def __init__(self, name, env) -> None:
        """Initialize with the keys in the dictionary to check.

        :type name: str
        :param name: The key with that name will be loaded and returned.

        :type env: dict
        :param env: Environment variables dictionary to get variables from.
        """
        ...

    def provide(self):
        """Provide a config value from a source dictionary."""
        ...

    def __repr__(self): ...

class SectionConfigProvider(BaseProvider):
    """Provides a dictionary from a section in the scoped config

    This is useful for retrieving scoped config variables (i.e. s3) that have
    their own set of config variables and resolving logic.
    """

    def __init__(self, section_name, session, override_providers=...) -> None: ...
    def provide(self): ...
    def __repr__(self): ...

class ConstantProvider(BaseProvider):
    """This provider provides a constant value."""

    def __init__(self, value) -> None: ...
    def provide(self):
        """Provide the constant value given during initialization."""
        ...

    def __repr__(self): ...
