"""
This type stub file was generated by pyright.
"""

import logging

logger = logging.getLogger(__name__)
class StreamingBody(object):
    """Wrapper class for an http response body.

    This provides a few additional conveniences that do not exist
    in the urllib3 model:

        * Set the timeout on the socket (i.e read() timeouts)
        * Auto validation of content length, if the amount of bytes
          we read does not match the content length, an exception
          is raised.

    """
    _DEFAULT_CHUNK_SIZE = ...
    def __init__(self, raw_stream, content_length) -> None:
        ...

    def set_socket_timeout(self, timeout):
        """Set the timeout seconds on the socket."""
        ...

    def read(self, amt=...):
        """Read at most amt bytes from the stream.

        If the amt argument is omitted, read all data.
        """
        ...

    def __iter__(self):
        """Return an iterator to yield 1k chunks from the raw stream.
        """
        ...

    def __next__(self):
        """Return the next 1k chunk from the raw stream.
        """
        ...

    next = ...
    def iter_lines(self, chunk_size=..., keepends=...):
        """Return an iterator to yield lines from the raw stream.

        This is achieved by reading chunk of bytes (of size chunk_size) at a
        time from the raw stream, and then yielding lines from there.
        """
        ...

    def iter_chunks(self, chunk_size=...):
        """Return an iterator to yield chunks of chunk_size bytes from the raw
        stream.
        """
        ...

    def close(self):
        """Close the underlying http response stream."""
        ...



def get_response(operation_model, http_response):
    ...
