"""This type stub file was generated by pyright."""

from __future__ import annotations

from docker.credentials.constants import *
from docker.credentials.errors import CredentialsNotFound, StoreError
from docker.credentials.store import Store
