"""This type stub file was generated by pyright."""

# pylint: disable=C,E,W,R
from __future__ import annotations

def find_executable(executable, path=...): ...
def create_environment_dict(overrides): ...
