"""This type stub file was generated by pyright."""

# pylint: disable=C,E,W,R
from __future__ import annotations

from docker import utils

log = ...

class BuildApiMixin:
    def build(
        self,
        path=...,
        tag=...,
        quiet=...,
        fileobj=...,
        nocache=...,
        rm=...,
        timeout=...,
        custom_context=...,
        encoding=...,
        pull=...,
        forcerm=...,
        dockerfile=...,
        container_limits=...,
        decode=...,
        buildargs=...,
        gzip=...,
        shmsize=...,
        labels=...,
        cache_from=...,
        target=...,
        network_mode=...,
        squash=...,
        extra_hosts=...,
        platform=...,
        isolation=...,
        use_config_proxy=...,
    ): ...
    @utils.minimum_version("1.31")
    def prune_builds(self): ...

def process_dockerfile(dockerfile, path): ...
