"""This type stub file was generated by pyright."""

from __future__ import annotations

from docker import utils

class ConfigApiMixin:
    @utils.minimum_version("1.30")
    def create_config(self, name, data, labels=...): ...
    @utils.minimum_version("1.30")
    @utils.check_resource("id")
    def inspect_config(self, id): ...
    @utils.minimum_version("1.30")
    @utils.check_resource("id")
    def remove_config(self, id): ...
    @utils.minimum_version("1.30")
    def configs(self, filters=...): ...
