"""This type stub file was generated by pyright."""

from __future__ import annotations

from docker import utils

class DaemonApiMixin:
    @utils.minimum_version("1.25")
    def df(self): ...
    def events(self, since=..., until=..., filters=..., decode=...): ...
    def info(self): ...
    def login(
        self,
        username,
        password=...,
        email=...,
        registry=...,
        reauth=...,
        dockercfg_path=...,
    ): ...
    def ping(self): ...
    def version(self, api_version=...): ...
