"""This type stub file was generated by pyright."""

# pylint: disable=C,E,W,R
from __future__ import annotations

from docker import utils

class ExecApiMixin:
    @utils.check_resource("container")
    def exec_create(
        self,
        container,
        cmd,
        stdout=...,
        stderr=...,
        stdin=...,
        tty=...,
        privileged=...,
        user=...,
        environment=...,
        workdir=...,
        detach_keys=...,
    ): ...
    def exec_inspect(self, exec_id): ...
    def exec_resize(self, exec_id, height=..., width=...): ...
    @utils.check_resource("exec_id")
    def exec_start(
        self, exec_id, detach=..., tty=..., stream=..., socket=..., demux=...
    ): ...
