"""This type stub file was generated by pyright."""

# pylint: disable=C,E,W,R
from __future__ import annotations

from docker.utils import check_resource, minimum_version

class NetworkApiMixin:
    def networks(self, names=..., ids=..., filters=...): ...
    def create_network(
        self,
        name,
        driver=...,
        options=...,
        ipam=...,
        check_duplicate=...,
        internal=...,
        labels=...,
        enable_ipv6=...,
        attachable=...,
        scope=...,
        ingress=...,
    ): ...
    @minimum_version("1.25")
    def prune_networks(self, filters=...): ...
    @check_resource("net_id")
    def remove_network(self, net_id): ...
    @check_resource("net_id")
    def inspect_network(self, net_id, verbose=..., scope=...): ...
    @check_resource("container")
    def connect_container_to_network(
        self,
        container,
        net_id,
        ipv4_address=...,
        ipv6_address=...,
        aliases=...,
        links=...,
        link_local_ips=...,
        driver_opt=...,
    ): ...
    @check_resource("container")
    def disconnect_container_from_network(self, container, net_id, force=...): ...
