"""This type stub file was generated by pyright."""

# pylint: disable=C,E,W,R
from __future__ import annotations

from docker import utils

class SecretApiMixin:
    @utils.minimum_version("1.25")
    def create_secret(self, name, data, labels=..., driver=...): ...
    @utils.minimum_version("1.25")
    @utils.check_resource("id")
    def inspect_secret(self, id): ...
    @utils.minimum_version("1.25")
    @utils.check_resource("id")
    def remove_secret(self, id): ...
    @utils.minimum_version("1.25")
    def secrets(self, filters=...): ...
