"""This type stub file was generated by pyright."""

from __future__ import annotations

from docker import utils

log = ...

class SwarmApiMixin:
    def create_swarm_spec(self, *args, **kwargs): ...
    @utils.minimum_version("1.24")
    def get_unlock_key(self): ...
    @utils.minimum_version("1.24")
    def init_swarm(
        self,
        advertise_addr=...,
        listen_addr=...,
        force_new_cluster=...,
        swarm_spec=...,
        default_addr_pool=...,
        subnet_size=...,
        data_path_addr=...,
    ): ...
    @utils.minimum_version("1.24")
    def inspect_swarm(self): ...
    @utils.check_resource("node_id")
    @utils.minimum_version("1.24")
    def inspect_node(self, node_id): ...
    @utils.minimum_version("1.24")
    def join_swarm(
        self,
        remote_addrs,
        join_token,
        listen_addr=...,
        advertise_addr=...,
        data_path_addr=...,
    ): ...
    @utils.minimum_version("1.24")
    def leave_swarm(self, force=...): ...
    @utils.minimum_version("1.24")
    def nodes(self, filters=...): ...
    @utils.check_resource("node_id")
    @utils.minimum_version("1.24")
    def remove_node(self, node_id, force=...): ...
    @utils.minimum_version("1.24")
    def unlock_swarm(self, key): ...
    @utils.minimum_version("1.24")
    def update_node(self, node_id, version, node_spec=...): ...
    @utils.minimum_version("1.24")
    def update_swarm(
        self,
        version,
        swarm_spec=...,
        rotate_worker_token=...,
        rotate_manager_token=...,
        rotate_manager_unlock_key=...,
    ): ...
