#!/usr/bin/env python
from __future__ import print_function
import sys

from r4y.cfngin.commands import Stacker
from r4y.cfngin.logger import setup_logging


if __name__ == "__main__":
    # No immediate plans to remove. Not to be done prior to 2.0
    print('DEPRECATION NOTICE: the "stacker-r4y" command has been '
          'deprecated in favor of "r4y run-stacker"', file=sys.stderr)

    stacker = Stacker(setup_logging=setup_logging)
    args = stacker.parse_args()
    stacker.configure(args)
    args.run(args)
