#!/usr/bin/env python
import logging
import sys

from runway.tfenv import TFEnv


if __name__ == "__main__":
    if len(sys.argv) in [2, 3] and sys.argv[1] == 'install':
        if len(sys.argv) == 3:
            TFEnv().install(sys.argv[2])
        else:
            TFEnv().install()
    else:
        logging.error('Use like "tfenv-runway install 0.12.0"')
        sys.exit(1)
