"""
This type stub file was generated by pyright.
"""

from botocore.docs.shape import ShapeDocumenter

class BaseExampleDocumenter(ShapeDocumenter):
    def document_example(self, section, shape, prefix=..., include=..., exclude=...):
        """Generates an example based on a shape

        :param section: The section to write the documentation to.

        :param shape: The shape of the operation.

        :param prefix: Anything to be included before the example

        :type include: Dictionary where keys are parameter names and
            values are the shapes of the parameter names.
        :param include: The parameter shapes to include in the documentation.

        :type exclude: List of the names of the parameters to exclude.
        :param exclude: The names of the parameters to exclude from
            documentation.
        """
        ...

    def document_recursive_shape(self, section, shape, **kwargs): ...
    def document_shape_default(
        self, section, shape, history, include=..., exclude=..., **kwargs
    ): ...
    def document_shape_type_string(
        self, section, shape, history, include=..., exclude=..., **kwargs
    ): ...
    def document_shape_type_list(
        self, section, shape, history, include=..., exclude=..., **kwargs
    ): ...
    def document_shape_type_structure(
        self, section, shape, history, include=..., exclude=..., **kwargs
    ): ...
    def document_shape_type_map(
        self, section, shape, history, include=..., exclude=..., **kwargs
    ): ...

class ResponseExampleDocumenter(BaseExampleDocumenter):
    EVENT_NAME = ...
    def document_shape_type_event_stream(self, section, shape, history, **kwargs): ...

class RequestExampleDocumenter(BaseExampleDocumenter):
    EVENT_NAME = ...
    def document_shape_type_structure(
        self, section, shape, history, include=..., exclude=..., **kwargs
    ): ...
