"""
This type stub file was generated by pyright.
"""

class ShapeDocumenter(object):
    EVENT_NAME = ...
    def __init__(self, service_name, operation_name, event_emitter, context=...) -> None: ...
    def traverse_and_document_shape(
        self,
        section,
        shape,
        history,
        include=...,
        exclude=...,
        name=...,
        is_required=...,
    ):
        """Traverses and documents a shape

        Will take a self class and call its appropriate methods as a shape
        is traversed.

        :param section: The section to document.

        :param history: A list of the names of the shapes that have been
            traversed.

        :type include: Dictionary where keys are parameter names and
            values are the shapes of the parameter names.
        :param include: The parameter shapes to include in the documentation.

        :type exclude: List of the names of the parameters to exclude.
        :param exclude: The names of the parameters to exclude from
            documentation.

        :param name: The name of the shape.

        :param is_required: If the shape is a required member.
        """
        ...
