"""
This type stub file was generated by pyright.
"""

class WaiterDocumenter(object):
    def __init__(self, client, service_waiter_model) -> None: ...
    def document_waiters(self, section):
        """Documents the various waiters for a service.

        :param section: The section to write to.
        """
        ...

def document_wait_method(
    section,
    waiter_name,
    event_emitter,
    service_model,
    service_waiter_model,
    include_signature=...,
):
    """Documents a the wait method of a waiter

    :param section: The section to write to

    :param waiter_name: The name of the waiter

    :param event_emitter: The event emitter to use to emit events

    :param service_model: The service model

    :param service_waiter_model: The waiter model associated to the service

    :param include_signature: Whether or not to include the signature.
        It is useful for generating docstrings.
    """
    ...
